2022-06-18 17:55:50	INFO	::casa	
2022-06-18 17:55:51	INFO	::casa	CASA Version MODULAR 6.4.3.27
2022-06-18 17:55:51	INFO	::casa	Can't import casatelemetry module.
2022-06-18 17:55:51	INFO	plotants::::casa	##########################################
2022-06-18 17:55:51	INFO	plotants::::casa	##### Begin Task: plotants           #####
2022-06-18 17:55:51	INFO	plotants::::casa	plotants( vis='/Volumes/Data/20170820/20220511/eovsa/IDB20220511_1830-1850.ms', figfile='', antindex=False, logpos=False, exclude='', checkbaselines=False, title='', showgui=True )
2022-06-18 17:55:51	INFO	msmetadata_cmpt.cc::open	Performing internal consistency checks on /Volumes/Data/20170820/20220511/eovsa/IDB20220511_1830-1850.ms...
2022-06-18 17:55:53	SEVERE	msmetadata_cmpt.cc::observatoryposition	Exception Reported: Exception: Telescope EOVSA is not recognized by CASA.
2022-06-18 17:55:53	SEVERE	msmetadata_cmpt.cc::observatoryposition+	... thrown by casa6core::MPosition casa6core::MSMetaData::getObservatoryPosition(casa6core::uInt) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 3276
2022-06-18 17:55:53	SEVERE	plotants::::casa	Task plotants raised an exception of class RuntimeError with the following message: Exception: Telescope EOVSA is not recognized by CASA.
2022-06-18 17:55:53	SEVERE	plotants::::casa+	... thrown by casa6core::MPosition casa6core::MSMetaData::getObservatoryPosition(casa6core::uInt) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 3276
2022-06-18 17:55:53	INFO	plotants::::casa	Task plotants complete. Start time: 2022-06-18 13:55:50.734483 End time: 2022-06-18 13:55:52.913492
2022-06-18 17:55:53	INFO	plotants::::casa	##### End Task: plotants             #####
2022-06-18 17:55:53	INFO	plotants::::casa	##########################################
2022-06-18 23:26:34	INFO	plotants::::casa	##########################################
2022-06-18 23:26:34	INFO	plotants::::casa	##### Begin Task: plotants           #####
2022-06-18 23:26:34	INFO	plotants::::casa	plotants( vis='/Volumes/Data/20170820/20220511/eovsa/play_ground/IDB20220511_1830-1850.ms', figfile='', antindex=False, logpos=False, exclude='', checkbaselines=False, title='', showgui=True )
2022-06-18 23:26:34	INFO	msmetadata_cmpt.cc::open	Performing internal consistency checks on /Volumes/Data/20170820/20220511/eovsa/play_ground/IDB20220511_1830-1850.ms...
2022-06-18 23:26:36	SEVERE	msmetadata_cmpt.cc::observatoryposition	Exception Reported: Exception: Telescope EOVSA is not recognized by CASA.
2022-06-18 23:26:36	SEVERE	msmetadata_cmpt.cc::observatoryposition+	... thrown by casa6core::MPosition casa6core::MSMetaData::getObservatoryPosition(casa6core::uInt) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 3276
2022-06-18 23:26:36	SEVERE	plotants::::casa	Task plotants raised an exception of class RuntimeError with the following message: Exception: Telescope EOVSA is not recognized by CASA.
2022-06-18 23:26:36	SEVERE	plotants::::casa+	... thrown by casa6core::MPosition casa6core::MSMetaData::getObservatoryPosition(casa6core::uInt) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 3276
2022-06-18 23:26:36	INFO	plotants::::casa	Task plotants complete. Start time: 2022-06-18 19:26:33.549952 End time: 2022-06-18 19:26:35.862067
2022-06-18 23:26:36	INFO	plotants::::casa	##### End Task: plotants             #####
2022-06-18 23:26:36	INFO	plotants::::casa	##########################################
2022-06-18 23:28:01	INFO	plotants::::casa	##########################################
2022-06-18 23:28:01	INFO	plotants::::casa	##### Begin Task: plotants           #####
2022-06-18 23:28:01	INFO	plotants::::casa	plotants( vis='/Volumes/Data/20170820/20220511/eovsa/play_ground/IDB20220511_1830-1850.ms', figfile='', antindex=False, logpos=False, exclude='', checkbaselines=False, title='', showgui=True )
2022-06-18 23:28:01	INFO	msmetadata_cmpt.cc::open	Performing internal consistency checks on /Volumes/Data/20170820/20220511/eovsa/play_ground/IDB20220511_1830-1850.ms...
2022-06-18 23:28:01	SEVERE	msmetadata_cmpt.cc::observatoryposition	Exception Reported: Exception: Telescope EOVSA is not recognized by CASA.
2022-06-18 23:28:01	SEVERE	msmetadata_cmpt.cc::observatoryposition+	... thrown by casa6core::MPosition casa6core::MSMetaData::getObservatoryPosition(casa6core::uInt) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 3276
2022-06-18 23:28:01	SEVERE	plotants::::casa	Task plotants raised an exception of class RuntimeError with the following message: Exception: Telescope EOVSA is not recognized by CASA.
2022-06-18 23:28:01	SEVERE	plotants::::casa+	... thrown by casa6core::MPosition casa6core::MSMetaData::getObservatoryPosition(casa6core::uInt) const at File: casacore/ms/MSOper/MSMetaData.cc, line: 3276
2022-06-18 23:28:01	INFO	plotants::::casa	Task plotants complete. Start time: 2022-06-18 19:28:00.995476 End time: 2022-06-18 19:28:01.050314
2022-06-18 23:28:01	INFO	plotants::::casa	##### End Task: plotants             #####
2022-06-18 23:28:01	INFO	plotants::::casa	##########################################
